# **Spatial Transcriptomics Deep Learning (STDL) Project Notebook**

> The notebook contains main experiments and examples of how to use the code

## **Phase 1: Pre-processing and technical preparations**

### 1.1: **Assign GPU device and allow CUDA debugging**

In [1]:
# create code to reimport module if i change it
%load_ext autoreload

In [2]:
# the next 2 lines are to allow debugging with CUDA !
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"  
print(f'cuda debugging allowed')

cuda debugging allowed


In [3]:
%%time

import torch
print(f'cuda device count: {torch.cuda.device_count()}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
#Additional Info when using cuda
if device.type == 'cuda':
    print(f'device name: {torch.cuda.get_device_name(0)}')
    print(f'torch.cuda.device(0): {torch.cuda.device(0)}')
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_cached(0)/1024**3,1), 'GB')
# NOTE: important !!!!!!
# clearing out the cache before beginning
torch.cuda.empty_cache()

cuda device count: 1
Using device: cuda
device name: GeForce RTX 2080 Ti
torch.cuda.device(0): <torch.cuda.device object at 0x7fdeb8348910>
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
CPU times: user 2.9 s, sys: 3.69 s, total: 6.59 s
Wall time: 1.26 s


### 1.2: **Import the Pre-Process module**

> `loadAndPreProcess` module contains methods to load the data files as pytorch and pandas objects, methods to preprocess the given data, and methods to create custom datasets from the preprocessed data.

<div class="alert alert-block alert-warning">
<b>TODO:</b> fill above line
</div>

In [4]:
# note: path to project is: /home/roy.rubin/STDLproject/
%autoreload 2
import loadAndPreProcess

### 1.3: **Load pytorch dataset objects from the image folder**

> loading regular and augmented datasets created from the given image folder with transformations.

> Note: `augmentedImageFolder` is a custom dataset of imageFolder objects with different transformations (see code).

> Note: `im_hight_and_width_size` will define the size to which the images in the folder will be resized to. their original size 176, and so if the number will be bigger, the images will be automaticaly upsampled in the `resize` (not sure by what method) - which means images might be "pixelized" / lower quality. The problem is, size 176 doesnt work with all models, so i had to increase the size.

In [5]:
im_hight_and_width_size = 176  # values: 176 (doesnt work with inception) / 224 (doesnt work with inception) / 299 (works with inception)

In [6]:
%%time

path_to_images_dir_patient1_train = "/home/roy.rubin/STDLproject/spatialGeneExpressionData/patient1/images"
imageFolder_train = loadAndPreProcess.load_dataset_from_images_folder(path_to_images_dir_patient1_train, im_hight_and_width_size)
augmentedImageFolder_train = loadAndPreProcess.load_augmented_imageFolder_DS_from_images_folder(path_to_images_dir_patient1_train, im_hight_and_width_size)


----- entered function load_dataset_from_pictures_folder -----

----- finished function load_dataset_from_pictures_folder -----


----- entered function load_dataset_from_pictures_folder -----

----- finished function load_dataset_from_pictures_folder -----

CPU times: user 234 ms, sys: 27.2 ms, total: 261 ms
Wall time: 265 ms


In [7]:
%%time

path_to_images_dir_patient2_test = "/home/roy.rubin/STDLproject/spatialGeneExpressionData/patient2/images"
imageFolder_test = loadAndPreProcess.load_dataset_from_images_folder(path_to_images_dir_patient2_test, im_hight_and_width_size)
# augmentedImageFolder_test = loadAndPreProcess.load_augmented_imageFolder_DS_from_images_folder(path_to_images_dir_patient2_test, im_hight_and_width_size) # not needed for now


----- entered function load_dataset_from_pictures_folder -----

----- finished function load_dataset_from_pictures_folder -----

CPU times: user 21.7 ms, sys: 2.47 ms, total: 24.2 ms
Wall time: 24.3 ms


### 1.4: **Load pandas dataframe objects from the given mtx/tsv/csv files**

> `matrix_dataframe` represents the gene expression count values of each sample for each gene

> `features_dataframe` contains the names of all the genes

> `barcodes_dataframe` contains the names of all the samples

In [8]:
%%time

path_to_mtx_tsv_files_dir_patient1_train = "/home/roy.rubin/STDLproject/spatialGeneExpressionData/patient1"
matrix_dataframe_train, features_dataframe_train , barcodes_dataframe_train = loadAndPreProcess.load_dataframes_from_mtx_and_tsv_new(path_to_mtx_tsv_files_dir_patient1_train)


----- entered function load_dataframes_from_mtx_and_tsv -----
started reading features.tsv
V  finished reading features.tsv
started reading barcodes.tsv
V  finished reading barcodes.tsv
started reading matrix.mtx. this might take some time ...
V  finished reading matrix.mtx
adjusting matrix_dataframe
V  finished working on matrix_dataframe

----- finished function load_dataframes_from_mtx_and_tsv -----

CPU times: user 1min 25s, sys: 1.24 s, total: 1min 27s
Wall time: 1min 27s


In [9]:
%%time

path_to_mtx_tsv_files_dir_patient2_test = "/home/roy.rubin/STDLproject/spatialGeneExpressionData/patient2"
matrix_dataframe_test, features_dataframe_test , barcodes_dataframe_test = loadAndPreProcess.load_dataframes_from_mtx_and_tsv_new(path_to_mtx_tsv_files_dir_patient2_test)


----- entered function load_dataframes_from_mtx_and_tsv -----
started reading features.tsv
V  finished reading features.tsv
started reading barcodes.tsv
V  finished reading barcodes.tsv
started reading matrix.mtx. this might take some time ...
V  finished reading matrix.mtx
adjusting matrix_dataframe
V  finished working on matrix_dataframe

----- finished function load_dataframes_from_mtx_and_tsv -----

CPU times: user 1min 19s, sys: 1.07 s, total: 1min 20s
Wall time: 1min 20s


### 1.5: **Remove samples from the matrix dataframe with no matching images in the image folder**

> Note: indices are being reset after this action, so a mapping of old to new column indices is returned: `column_mapping`.

> Note: the dataframe is also reordered according to the images order in the image folder

In [10]:
%%time

matrix_dataframe_train, column_mapping_train = loadAndPreProcess.cut_samples_with_no_matching_image_and_reorder_df(matrix_df=matrix_dataframe_train, 
                                                                                                                    image_folder_of_the_df=imageFolder_train, 
                                                                                                                    barcodes_df=barcodes_dataframe_train)

cutting samples that dont have mathching images in the image folder from the dataframe ...
V   done :)

CPU times: user 26.9 s, sys: 1.19 s, total: 28.1 s
Wall time: 28.1 s


In [11]:
%%time

matrix_dataframe_test, column_mapping_test = loadAndPreProcess.cut_samples_with_no_matching_image_and_reorder_df(matrix_df=matrix_dataframe_test, 
                                                                                                                  image_folder_of_the_df=imageFolder_test, 
                                                                                                                  barcodes_df=barcodes_dataframe_test)

cutting samples that dont have mathching images in the image folder from the dataframe ...
V   done :)

CPU times: user 33.6 s, sys: 828 ms, total: 34.4 s
Wall time: 34.4 s


### 1.6: **Remove less-informative genes**

> we define *less-informative* genes as genes with less than K counts over all samples

> `Base_value` is a parameter for the user's choice

> Note: indices are being reset after this action, so a mapping of old to new column indices is returned: `row_mapping`.

In [12]:
%%time

# begin by asserting that our dataframes have the same genes to begin with using the metadata of features_dataframe
assert features_dataframe_train['gene_names'].equals(features_dataframe_test['gene_names'])

Base_value = 10
matrix_dataframe_train, matrix_dataframe_test, row_mapping = loadAndPreProcess.cut_genes_with_under_B_counts_from_train_and_test(matrix_dataframe_train, matrix_dataframe_test, Base_value) 

checking for genes (rows) that contain less than B counts in both dataframes ...
discarding relevant rows ...
CPU times: user 45.3 s, sys: 2.48 s, total: 47.8 s
Wall time: 47.9 s


### 1.7: **Normalize matrix_dataframe entries**

> normaliztion will be performed on the remainning rows of the dataframe with the logic "log 1P"

> This method Calculates log(1 + x)

In [13]:
%%time

matrix_dataframe_train = loadAndPreProcess.perform_log_1p_normalization(matrix_dataframe_train) 

performing log1P transformation of the dataframe ...

CPU times: user 1.57 s, sys: 27.9 ms, total: 1.59 s
Wall time: 1.59 s


In [14]:
%%time

matrix_dataframe_test = loadAndPreProcess.perform_log_1p_normalization(matrix_dataframe_test) 

performing log1P transformation of the dataframe ...

CPU times: user 1.69 s, sys: 23.8 ms, total: 1.71 s
Wall time: 1.71 s


> We have performed all of the pre-processing actions on our matrix dataframes. (more pre-processing is still needed our datasets)

> print some information regarding our dataframes

In [15]:
import projectUtilities
projectUtilities.printInfoAboutReducedDF(matrix_dataframe_train)
print("\n****\n")
projectUtilities.printInfoAboutReducedDF(matrix_dataframe_test)


print data regarding the reduced dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18077 entries, 0 to 18076
Columns: 3813 entries, 0 to 3812
dtypes: Sparse[float64, 0.0](3813)
memory usage: 220.7 MB
None
   0         1     2     3     4         5     6     7         8     9     \
0   0.0  0.000000   0.0   0.0   0.0  0.693147   0.0   0.0  0.000000   0.0   
1   0.0  1.098612   0.0   0.0   0.0  0.000000   0.0   0.0  0.693147   0.0   
2   0.0  0.000000   0.0   0.0   0.0  0.000000   0.0   0.0  0.000000   0.0   
3   0.0  0.000000   0.0   0.0   0.0  0.000000   0.0   0.0  0.000000   0.0   
4   0.0  0.693147   0.0   0.0   0.0  0.000000   0.0   0.0  0.000000   0.0   

   ...  3803  3804      3805  3806  3807  3808  3809  3810  3811  3812  
0  ...   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1  ...   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2  ...   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3  ...   0.0   0.0  0.000000

### 1.8: **Create custom datasets**

> Each custom dataset is tailored per task

> there are four tasks: single gene prediction, k gene prediction, all gene prediction using NMF dim. reduction, all gene prediction using AE dim. reduction

> For each of the above tasks 2 datasets were created:

>> A Dataset created from the TRAIN data WITHOUT augmentation (without image transformations)

>> A Dataset created from the TRAIN data WITH augmentation (with image transformations)

>> A Dataset created from the TEST data WITHOUT augmentation (without image transformations)

In [16]:
%%time

## choose gene
gene_name = 'CRISP3'  # was changed from 'BRCA1' because CRISP3 has the (almost) highest variance in both the train and test datasets.
                      # NOTE: the gene 'CRISP3' is "upregulated in certain types of prostate cancer" according to
                      #       https://www.genecards.org/cgi-bin/carddisp.pl?gene=CRISP3&keywords=rich
                      # IMPORTANT ASSUMPTION: the chosen gene here actually appears in all reduced matrix dataframes (train and test) or the code might not work
from projectUtilities import get_variance_of_gene
gene_variance_value = get_variance_of_gene(gene_name=gene_name, matrix_df=matrix_dataframe_train, row_mapping=row_mapping, features_df=features_dataframe_train)
print(f'The chosen gene is {gene_name} and its variance is {gene_variance_value}')

## create datasets
custom_DS_SingleValuePerImg_augmented = loadAndPreProcess.STDL_Dataset_SingleValuePerImg(imageFolder=augmentedImageFolder_train, 
                                                               matrix_dataframe=matrix_dataframe_train, 
                                                               features_dataframe=features_dataframe_train, 
                                                               barcodes_dataframe=barcodes_dataframe_train, 
                                                               column_mapping=column_mapping_train,
                                                               row_mapping=row_mapping,
                                                               chosen_gene_name=gene_name)
custom_DS_SingleValuePerImg_test = loadAndPreProcess.STDL_Dataset_SingleValuePerImg(imageFolder=imageFolder_test, 
                                                               matrix_dataframe=matrix_dataframe_test, 
                                                               features_dataframe=features_dataframe_test, 
                                                               barcodes_dataframe=barcodes_dataframe_test, 
                                                               column_mapping=column_mapping_test,
                                                               row_mapping=row_mapping,
                                                               chosen_gene_name=gene_name)

The chosen gene is CRISP3 and its variance is 1.3530372139065492

----- entering __init__ phase of  STDL_Dataset_SingleValuePerImg -----

----- finished __init__ phase of  STDL_Dataset_SingleValuePerImg -----


----- entering __init__ phase of  STDL_Dataset_SingleValuePerImg -----

----- finished __init__ phase of  STDL_Dataset_SingleValuePerImg -----

CPU times: user 857 ms, sys: 72 ms, total: 929 ms
Wall time: 926 ms


<div class="alert alert-block alert-info">
<b>Note:</b> inside the init phase of `STDL_Dataset_KValuesPerImg_KGenesWithHighestVariance` class, K genes with the highest variance are chosen from matrix_dataframe, and they are the only genes that are kept for training and testing purposes
</div>

In [17]:
%%time

k = 10

custom_DS_KGenesWithHighestVariance_augmented = loadAndPreProcess.STDL_Dataset_KValuesPerImg_KGenesWithHighestVariance(imageFolder=augmentedImageFolder_train, 
                                                                           matrix_dataframe=matrix_dataframe_train, 
                                                                           features_dataframe=features_dataframe_train, 
                                                                           barcodes_dataframe=barcodes_dataframe_train, 
                                                                           column_mapping=column_mapping_train,
                                                                           row_mapping=row_mapping,
                                                                           num_of_dims_k=k)
custom_DS_KGenesWithHighestVariance_test = loadAndPreProcess.STDL_Dataset_KValuesPerImg_KGenesWithHighestVariance(imageFolder=imageFolder_test, 
                                                                           matrix_dataframe=matrix_dataframe_test, 
                                                                           features_dataframe=features_dataframe_test, 
                                                                           barcodes_dataframe=barcodes_dataframe_test, 
                                                                           column_mapping=column_mapping_test,
                                                                           row_mapping=row_mapping,                                                                                                                  
                                                                           num_of_dims_k=k)


----- entering __init__ phase of  STDL_Dataset_KValuesPerImg_KGenesWithHighestVariance -----
calculate variance of all columns from  matrix_dataframe - and choosing K genes with higest variance ...
the K genes with the highest variance are:
      gene_names  variance
15326      COX6C  1.384259
10975     CRISP3  1.353037
6665        CPB1  1.328052
20428        MGP  1.309196
13994     TCEAL4  1.237330
9549      CXCL14  1.215041
5098      IGFBP5  1.177371
18155      CCND1  1.167686
11978       AGR2  1.163414
20840       KRT8  1.158179

----- finished __init__ phase of  STDL_Dataset_LatentTensor -----


----- entering __init__ phase of  STDL_Dataset_KValuesPerImg_KGenesWithHighestVariance -----
calculate variance of all columns from  matrix_dataframe - and choosing K genes with higest variance ...
the K genes with the highest variance are:
      gene_names  variance
10975     CRISP3  1.301761
6665        CPB1  1.259807
9549      CXCL14  1.217983
32395      IGLC2  1.125526
4026        IGKC

<div class="alert alert-block alert-info">
<b>Note:</b> inside the init phase of `STDL_Dataset_KValuesPerImg_LatentTensor_NMF` class, an NMF decompositionis performed on the matrix_dataframe object
</div>

In [18]:
%%time

k = 10

custom_DS_LatentTensor_NMF_augmented = loadAndPreProcess.STDL_Dataset_KValuesPerImg_LatentTensor_NMF(imageFolder=augmentedImageFolder_train, 
                                                                           matrix_dataframe=matrix_dataframe_train, 
                                                                           features_dataframe=features_dataframe_train, 
                                                                           barcodes_dataframe=barcodes_dataframe_train, 
                                                                           column_mapping=column_mapping_train,
                                                                           num_of_dims_k=k)
custom_DS_LatentTensor_NMF_test = loadAndPreProcess.STDL_Dataset_KValuesPerImg_LatentTensor_NMF(imageFolder=imageFolder_test, 
                                                                           matrix_dataframe=matrix_dataframe_test, 
                                                                           features_dataframe=features_dataframe_test, 
                                                                           barcodes_dataframe=barcodes_dataframe_test, 
                                                                           column_mapping=column_mapping_test,
                                                                           num_of_dims_k=k)


----- entering __init__ phase of  STDL_Dataset_KValuesPerImg_LatentTensor_NMF -----
performing NMF decomposition on main matrix dataframe ...

----- finished __init__ phase of  STDL_Dataset_LatentTensor -----


----- entering __init__ phase of  STDL_Dataset_KValuesPerImg_LatentTensor_NMF -----
performing NMF decomposition on main matrix dataframe ...

----- finished __init__ phase of  STDL_Dataset_LatentTensor -----

CPU times: user 19min 5s, sys: 8min 47s, total: 27min 52s
Wall time: 41.9 s


<div class="alert alert-block alert-info">
<b>Note:</b> 
<ul>
  <li>first we create a dataset from `matrix_dataframe_train` to feed our AEnet.</li>
  <li>Then we create our AEnet and train it.</li>
  <li>Finally, we create our `custom_DS_LatentTensor_AE` class, in which the Autoencoder network will be saved.</li>
</ul>
</div>

In [19]:
dataset_from_matrix_df = loadAndPreProcess.STDL_Dataset_matrix_df_for_AE_init(matrix_dataframe_train)

In [20]:
%%time

from executionModule import get_Trained_AEnet
k = 10
AEnet = get_Trained_AEnet(dataset_from_matrix_df=dataset_from_matrix_df, z_dim=k, num_of_epochs=3, device=device)  # NOTE: tweak num_of_epochs as wanted.


----- entered function return_trained_AE_net -----
note - number of (hidden) linear layers is supposed to be 3

entered __init__ of AutoencoderNet
****** begin training ******
iteration 1 of 3 epochs
iteration 2 of 3 epochs
iteration 3 of 3 epochs
finished all epochs !                                         
which means, that this model is now trained.
plotting the loss convergence for the training of this model: 

----- entered function plot_loss_convergence -----

----- finished function plot_loss_convergence -----

----- finished function return_trained_AE_net -----

CPU times: user 3min 9s, sys: 25.7 s, total: 3min 35s
Wall time: 3min 39s


In [21]:
%%time

k = 10

custom_DS_LatentTensor_AE_augmented = loadAndPreProcess.STDL_Dataset_KValuesPerImg_LatentTensor_AutoEncoder(imageFolder=augmentedImageFolder_train, 
                                                                           matrix_dataframe=matrix_dataframe_train, 
                                                                           features_dataframe=features_dataframe_train, 
                                                                           barcodes_dataframe=barcodes_dataframe_train, 
                                                                           AEnet=AEnet,                                                                                                            
                                                                           column_mapping=column_mapping_train,
                                                                           num_of_dims_k=k,
                                                                           device=device)
custom_DS_LatentTensor_AE_test = loadAndPreProcess.STDL_Dataset_KValuesPerImg_LatentTensor_AutoEncoder(imageFolder=imageFolder_test, 
                                                                           matrix_dataframe=matrix_dataframe_test, 
                                                                           features_dataframe=features_dataframe_test, 
                                                                           barcodes_dataframe=barcodes_dataframe_test, 
                                                                           AEnet=AEnet,                                                                                                       
                                                                           column_mapping=column_mapping_test,
                                                                           num_of_dims_k=k,
                                                                           device=device)


----- entering __init__ phase of  STDL_Dataset_KValuesPerImg_LatentTensor_AutoEncoder -----
initializing the autoencoder (this might take a while) ...

----- finished __init__ phase of  STDL_Dataset_KValuesPerImg_LatentTensor_AutoEncoder -----


----- entering __init__ phase of  STDL_Dataset_KValuesPerImg_LatentTensor_AutoEncoder -----
initializing the autoencoder (this might take a while) ...

----- finished __init__ phase of  STDL_Dataset_KValuesPerImg_LatentTensor_AutoEncoder -----

CPU times: user 936 ms, sys: 736 ms, total: 1.67 s
Wall time: 1.67 s


### 1.9: prepare for the next phases in which the experiments are executed

> import `executionModule` which contains the experiments, training methods, and testing methods

> create `hyperparameters` dictionary which will contain all of the hyper-parameters for our experiments (note - user can change these later)

> create `model_list` that will hold all the names for the models that will be used (only 3 models for now, as can be seen below). the models are:

>> `BasicConvNet` model

>> `DensetNet121` model

>> `Inception_V3` model

<div class="alert alert-block alert-warning">
<b>Warning:</b> change the hyper-parameters below with caution if needed !
</div>

In [79]:
%autoreload 2
import executionModule

# define hyperparameters for the TRAINING of the models (NOT the testing phases of the experiments)
hyperparameters = dict()
hyperparameters['batch_size'] = 30
hyperparameters['max_alowed_number_of_batches'] = 20 #<--------------------------change to inf or 99999. anythin below 1220 will cut some batches ... this is only used to speed up training
hyperparameters['precent_of_dataset_allocated_for_training'] = 0.8
hyperparameters['learning_rate'] = 1e-4
hyperparameters['momentum'] = 0.9
hyperparameters['num_of_epochs'] = 2 #<------------------------------------------change to 5 at least
hyperparameters['num_workers'] = 2 #<---- NOTE: default is 0, means everything happens serially. testing 2 now !.
                                   # see: https://pytorch.org/docs/stable/data.html#single-and-multi-process-data-loading

# define hyperparameters for BsicConvNet
hyperparameters['channels'] = [32, 32, 64, 64] 
hyperparameters['num_of_convolution_layers'] = len(hyperparameters['channels'])
hyperparameters['hidden_dims'] = [100, 100]
hyperparameters['num_of_hidden_layers'] = len(hyperparameters['hidden_dims'])
hyperparameters['pool_every'] = 99999

# add the chosen single gene's index to the hyperparameters
from projectUtilities import get_index_of_gene_by_name
hyperparameters['gene_name'] = gene_name
hyperparameters['geneRowIndexIn_Reduced_Train_matrix_df'], hyperparameters['geneRowIndexIn_Original_Train_matrix_df'] = get_index_of_gene_by_name(gene_name=gene_name, matrix_df=matrix_dataframe_train, row_mapping=row_mapping, features_df=features_dataframe_train)
hyperparameters['geneRowIndexIn_Reduced_Test_matrix_df'], hyperparameters['geneRowIndexIn_Original_Test_matrix_df'] = get_index_of_gene_by_name(gene_name=gene_name, matrix_df=matrix_dataframe_test, row_mapping=row_mapping, features_df=features_dataframe_test)

# list of all models used
model_list = []
model_list.append('BasicConvNet')
model_list.append('DensetNet121')


> We add the code before the plots to show them correctly `%matplotlib inline`

In [23]:
%matplotlib inline

<div class="alert alert-block alert-info">
<b>Note:</b> In each experiment, the model is trained with the augmented train dataset, and then tested on the test dataset
    (NMF and AE experiments also test on the regular train dataset after training is done)
</div>

## Phase 2: Single Gene Prediction

In [ ]:
%%time

executionModule.runExperiment(ds_train=custom_DS_SingleValuePerImg_augmented, 
                                ds_test=custom_DS_SingleValuePerImg_test,
                                hyperparams=hyperparameters, 
                                device=device, 
                                model_name='BasicConvNet', 
                                dataset_name='single_gene ')

In [25]:
# %%time

# executionModule.runExperiment(ds_train=custom_DS_SingleValuePerImg_augmented, 
#                                 ds_test=custom_DS_SingleValuePerImg_test,
#                                 hyperparams=hyperparameters, 
#                                 device=device, 
#                                 model_name='DensetNet121', 
#                                 dataset_name='single_gene ')

## Phase 3: K genes prediction

In [ ]:
%%time

executionModule.runExperiment(ds_train=custom_DS_KGenesWithHighestVariance_augmented, 
                                ds_test=custom_DS_KGenesWithHighestVariance_test,
                                hyperparams=hyperparameters, 
                                device=device, 
                                model_name='BasicConvNet', 
                                dataset_name='k_genes ')

In [27]:
# %%time

# executionModule.runExperiment(ds_train=custom_DS_KGenesWithHighestVariance_augmented, 
#                                 ds_test=custom_DS_KGenesWithHighestVariance_test,
#                                 hyperparams=hyperparameters, 
#                                 device=device, 
#                                 model_name='DensetNet121', 
#                                 dataset_name='k_genes ')

## Phase 4: All genes prediction - using dimensionality reduction techniques

### 4.1: Prediction using dimensionality reduction technique NMF

In [80]:
%%time

executionModule.runExperiment(ds_train=custom_DS_LatentTensor_NMF_augmented, 
                                ds_test=custom_DS_LatentTensor_NMF_test,
                                hyperparams=hyperparameters, 
                                device=device, 
                                model_name='BasicConvNet', 
                                dataset_name='NMF ')


----- entered function runExperiment -----
/ * \ ENTERED train_prediction_model / * \ 
NOTE: in order to speed up training (while damaging accuracy) the number of batches per epoch was reduced from 1016 to 20
****** begin training ******
iteration 1 of 2 epochs
iteration 2 of 2 epochs
finished all epochs !                                         
which means, that this model is now trained.
plotting the loss convergence for the training of this model: 

----- entered function plot_loss_convergence -----

----- finished function plot_loss_convergence -----
 \ * / FINISHED train_prediction_model \ * / 

## perform on TRAIN data ##

----- entered function getFullDimsPrediction_with_NMF_DS -----

----- finished function getKDimPrediction -----
matrix comparsions on all genes ...
distance between M_truth, M_pred: 7.019420702803787e-05
distance between M_truth, Baseline: 3.8139701375500744e-05
distance between M_pred, Baseline: 5.8892469566212774e-05
results plot & vector comparsions on the

In [29]:
# %%time

# executionModule.runExperiment(ds_train=custom_DS_LatentTensor_NMF_augmented, 
#                                 ds_test=custom_DS_LatentTensor_NMF_test,
#                                 hyperparams=hyperparameters, 
#                                 device=device, 
#                                 model_name='DensetNet121', 
#                                 dataset_name='NMF ')

### 4.2: Prediction using dimensionality reduction technique AE

In [81]:
%%time

hyperparameters['num_of_epochs'] = 0

executionModule.runExperiment(ds_train=custom_DS_LatentTensor_AE_augmented, 
                                ds_test=custom_DS_LatentTensor_AE_test,
                                hyperparams=hyperparameters, 
                                device=device, 
                                model_name='BasicConvNet', 
                                dataset_name='AE ')


----- entered function runExperiment -----
/ * \ ENTERED train_prediction_model / * \ 
NOTE: in order to speed up training (while damaging accuracy) the number of batches per epoch was reduced from 1016 to 20
****** begin training ******
finished all epochs !                                         
which means, that this model is now trained.
plotting the loss convergence for the training of this model: 

----- entered function plot_loss_convergence -----

----- finished function plot_loss_convergence -----
 \ * / FINISHED train_prediction_model \ * / 

## perform on TRAIN data ##

----- entered function getFullDimsPrediction_with_AE_DS -----

----- finished function getFullDimsPrediction_with_AE_DS -----

----- entered function getAutoEncoder_M_fast_reconstruction -----
batch 3813 of 3813 batches
----- finished function getAutoEncoder_M_fast_reconstruction -----
matrix comparsions on all genes ...
distance between M_truth, M_pred: 7.581811000105335e-05
distance between M_truth, Base

/home/roy.rubin/STDLproject/projectUtilities.py:380: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(8,8))



----- finished function plot_Single_Gene_PredAndTrue -----

## perform on TEST data ##

----- entered function getFullDimsPrediction_with_AE_DS -----

----- finished function getFullDimsPrediction_with_AE_DS -----
matrix comparsions on all genes ...
distance between M_truth, M_pred: 7.301726689644475e-05
distance between M_truth, Baseline: 4.673228895567077e-05
distance between M_pred, Baseline: 5.6236015651385795e-05
results plot & vector comparsions on the chosen single gene ...
distance between M_truth, M_pred: 0.023631136021437987
distance between M_truth, Baseline: 0.018084382932968556
distance between M_pred, Baseline: 0.017010916456694482

----- entered function plot_SingleGene_PredAndTrue_ScatterComparison -----

----- entered function plot_SingleGene_PredAndTrue_ColorVisualisation -----
finished preparing the plots, now just need to show on screen ....


/home/roy.rubin/STDLproject/projectUtilities.py:380: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(8,8))



----- finished function plot_Single_Gene_PredAndTrue -----

----- finished function runExperiment -----
CPU times: user 9min 12s, sys: 8min 22s, total: 17min 35s
Wall time: 17min 21s


In [31]:
# %%time

# executionModule.runExperiment(ds_train=custom_DS_LatentTensor_AE_augmented, 
#                                 ds_test=custom_DS_LatentTensor_AE_test,
#                                 hyperparams=hyperparameters, 
#                                 device=device, 
#                                 model_name='DensetNet121', 
#                                 dataset_name='AE ')

<div class="alert alert-block alert-danger">
<b>Note:</b> below this - everything is a testing block
</div>

In [33]:
import numpy as np
temp = np.random.rand(3,2)
print(temp)
print("***")
print(len(temp))
print("***")
print(temp.size)


[[0.04204044 0.82069342]
 [0.70913043 0.47583602]
 [0.19047911 0.45901468]]
***
3
***
6


In [34]:
from matplotlib import pyplot as plt
plt.figure(figsize=(8,8))
plt.savefig(f'old_files/testimg.png', bbox_inches='tight')

In [74]:
data = np.arange(15).reshape((5,3))
print(data)
print("***")
print(np.average(data, axis=0))
print("***")
print(np.average(data, axis=1))
print("***")
print(np.average(data, axis=1).reshape(-1,1))
print("***")

print(np.tile(A=np.average(data, axis=1).reshape(-1,1), reps=(1,3)))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
***
[6. 7. 8.]
***
[ 1.  4.  7. 10. 13.]
***
[[ 1.]
 [ 4.]
 [ 7.]
 [10.]
 [13.]]
***
[[ 1.  1.  1.]
 [ 4.  4.  4.]
 [ 7.  7.  7.]
 [10. 10. 10.]
 [13. 13. 13.]]


In [65]:


## das sa dsadas asd

## sad asdawafdawf
print('hi')


hi
